"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Game_Screen = exports.Game_Player = exports.Game_Picture = exports.Game_Party = exports.Game_Message = exports.Game_Map = exports.Game_Item = exports.Game_Interpreter = exports.Game_Followers = exports.Game_Follower = exports.Game_Event = exports.Game_Enemy = exports.Game_CommonEvent = exports.Game_CharacterBase = exports.Game_Character = exports.Game_BattlerBase = exports.Game_Battler = exports.Game_Actors = exports.Game_Actor = exports.Game_ActionResult = exports.Game_Action = exports.ConfigManager = exports.BattleManager = exports.AudioManager = exports.TextManager = exports.StorageManager = exports.SoundManager = exports.SceneManager = exports.PluginManager = exports.ImageManager = exports.WindowLayer = exports.Window = exports.Weather = exports.Utils = exports.TouchInput = exports.ToneSprite = exports.ToneFilter = exports.TilingSprite = exports.Tilemap = exports.Stage = exports.Sprite = exports.ScreenSprite = exports.RequestQueue = exports.Rectangle = exports.JsonEx = exports.Input = exports.ImageCache = exports.Graphics = exports.Bitmap = exports.DataManager = void 0;
exports.Window_BattleItem = exports.Window_BattleEnemy = exports.Window_BattleActor = exports.Window_Base = exports.Window_ActorCommand = exports.Spriteset_Map = exports.Spriteset_Battle = exports.Spriteset_Base = exports.Sprite_Weapon = exports.Sprite_Timer = exports.Sprite_StateOverlay = exports.Sprite_StateIcon = exports.Sprite_Picture = exports.Sprite_Enemy = exports.Sprite_Destination = exports.Sprite_Damage = exports.Sprite_Character = exports.Sprite_Battler = exports.Sprite_Base = exports.Sprite_Balloon = exports.Sprite_Animation = exports.Sprite_Actor = exports.Scene_Save = exports.Scene_Load = exports.Scene_File = exports.Scene_Title = exports.Scene_Status = exports.Scene_Skill = exports.Scene_Shop = exports.Scene_Options = exports.Scene_MenuBase = exports.Scene_Menu = exports.Scene_Map = exports.Scene_ItemBase = exports.Scene_Item = exports.Scene_Gameover = exports.Scene_GameEnd = exports.Scene_Equip = exports.Scene_Boot = exports.Scene_Battle = exports.Scene_Base = exports.Game_Vehicle = exports.Game_Variables = exports.Game_Unit = exports.Game_Troop = exports.Game_Timer = exports.Game_Temp = exports.Game_System = exports.Game_Switches = exports.Game_SelfSwitches = void 0;
exports.Window_SavefileList = exports.Window_TitleCommand = exports.Window_Status = exports.Window_SkillType = exports.Window_SkillStatus = exports.Window_SkillList = exports.Window_ShopStatus = exports.Window_ShopSell = exports.Window_ShopNumber = exports.Window_ShopCommand = exports.Window_ShopBuy = exports.Window_Selectable = exports.Window_ScrollText = exports.Window_PartyCommand = exports.Window_Options = exports.Window_NumberInput = exports.Window_Message = exports.Window_MenuStatus = exports.Window_MenuCommand = exports.Window_MenuActor = exports.Window_MapName = exports.Window_ItemList = exports.Window_ItemCategory = exports.Window_HorzCommand = exports.Window_Help = exports.Window_Gold = exports.Window_GameEnd = exports.Window_EventItem = exports.Window_EquipStatus = exports.Window_EquipSlot = exports.Window_EquipItem = exports.Window_EquipCommand = exports.Window_Command = exports.Window_ChoiceList = exports.Window_BattleSkill = exports.Window_BattleLog = void 0;
var DataManager_1 = require("./managers/DataManager");
Object.defineProperty(exports, "DataManager", { enumerable: true, get: function () { return DataManager_1.DataManager; } });
__exportStar(require("./managers/globals"), exports);
var Bitmap_1 = require("./core/Bitmap");
Object.defineProperty(exports, "Bitmap", { enumerable: true, get: function () { return Bitmap_1.Bitmap; } });
var Graphics_1 = require("./core/Graphics");
Object.defineProperty(exports, "Graphics", { enumerable: true, get: function () { return Graphics_1.Graphics; } });
var ImageCache_1 = require("./core/ImageCache");
Object.defineProperty(exports, "ImageCache", { enumerable: true, get: function () { return ImageCache_1.ImageCache; } });
var Input_1 = require("./core/Input");
Object.defineProperty(exports, "Input", { enumerable: true, get: function () { return Input_1.Input; } });
var JsonEx_1 = require("./core/JsonEx");
Object.defineProperty(exports, "JsonEx", { enumerable: true, get: function () { return JsonEx_1.JsonEx; } });
var Rectangle_1 = require("./core/Rectangle");
Object.defineProperty(exports, "Rectangle", { enumerable: true, get: function () { return Rectangle_1.Rectangle; } });
var RequestQueue_1 = require("./core/RequestQueue");
Object.defineProperty(exports, "RequestQueue", { enumerable: true, get: function () { return RequestQueue_1.RequestQueue; } });
var ScreenSprite_1 = require("./core/ScreenSprite");
Object.defineProperty(exports, "ScreenSprite", { enumerable: true, get: function () { return ScreenSprite_1.ScreenSprite; } });
var Sprite_1 = require("./core/Sprite");
Object.defineProperty(exports, "Sprite", { enumerable: true, get: function () { return Sprite_1.Sprite; } });
var Stage_1 = require("./core/Stage");
Object.defineProperty(exports, "Stage", { enumerable: true, get: function () { return Stage_1.Stage; } });
var Tilemap_1 = require("./core/Tilemap");
Object.defineProperty(exports, "Tilemap", { enumerable: true, get: function () { return Tilemap_1.Tilemap; } });
var TilingSprite_1 = require("./core/TilingSprite");
Object.defineProperty(exports, "TilingSprite", { enumerable: true, get: function () { return TilingSprite_1.TilingSprite; } });
var ToneFilter_1 = require("./core/ToneFilter");
Object.defineProperty(exports, "ToneFilter", { enumerable: true, get: function () { return ToneFilter_1.ToneFilter; } });
var ToneSprite_1 = require("./core/ToneSprite");
Object.defineProperty(exports, "ToneSprite", { enumerable: true, get: function () { return ToneSprite_1.ToneSprite; } });
var TouchInput_1 = require("./core/TouchInput");
Object.defineProperty(exports, "TouchInput", { enumerable: true, get: function () { return TouchInput_1.TouchInput; } });
var Utils_1 = require("./core/Utils");
Object.defineProperty(exports, "Utils", { enumerable: true, get: function () { return Utils_1.Utils; } });
var Weather_1 = require("./core/Weather");
Object.defineProperty(exports, "Weather", { enumerable: true, get: function () { return Weather_1.Weather; } });
var Window_1 = require("./core/Window");
Object.defineProperty(exports, "Window", { enumerable: true, get: function () { return Window_1.Window; } });
var WindowLayer_1 = require("./core/WindowLayer");
Object.defineProperty(exports, "WindowLayer", { enumerable: true, get: function () { return WindowLayer_1.WindowLayer; } });
var ImageManager_1 = require("./managers/ImageManager");
Object.defineProperty(exports, "ImageManager", { enumerable: true, get: function () { return ImageManager_1.ImageManager; } });
var PluginManager_1 = require("./managers/PluginManager");
Object.defineProperty(exports, "PluginManager", { enumerable: true, get: function () { return PluginManager_1.PluginManager; } });
var SceneManager_1 = require("./managers/SceneManager");
Object.defineProperty(exports, "SceneManager", { enumerable: true, get: function () { return SceneManager_1.SceneManager; } });
var SoundManager_1 = require("./managers/SoundManager");
Object.defineProperty(exports, "SoundManager", { enumerable: true, get: function () { return SoundManager_1.SoundManager; } });
var StorageManager_1 = require("./managers/StorageManager");
Object.defineProperty(exports, "StorageManager", { enumerable: true, get: function () { return StorageManager_1.StorageManager; } });
var TextManager_1 = require("./managers/TextManager");
Object.defineProperty(exports, "TextManager", { enumerable: true, get: function () { return TextManager_1.TextManager; } });
var AudioManager_1 = require("./managers/AudioManager");
Object.defineProperty(exports, "AudioManager", { enumerable: true, get: function () { return AudioManager_1.AudioManager; } });
var BattleManager_1 = require("./managers/BattleManager");
Object.defineProperty(exports, "BattleManager", { enumerable: true, get: function () { return BattleManager_1.BattleManager; } });
var ConfigManager_1 = require("./managers/ConfigManager");
Object.defineProperty(exports, "ConfigManager", { enumerable: true, get: function () { return ConfigManager_1.ConfigManager; } });
var GameAction_1 = require("./objects/GameAction");
Object.defineProperty(exports, "Game_Action", { enumerable: true, get: function () { return GameAction_1.Game_Action; } });
var GameActionResult_1 = require("./objects/GameActionResult");
Object.defineProperty(exports, "Game_ActionResult", { enumerable: true, get: function () { return GameActionResult_1.Game_ActionResult; } });
var GameActor_1 = require("./objects/GameActor");
Object.defineProperty(exports, "Game_Actor", { enumerable: true, get: function () { return GameActor_1.Game_Actor; } });
var GameActors_1 = require("./objects/GameActors");
Object.defineProperty(exports, "Game_Actors", { enumerable: true, get: function () { return GameActors_1.Game_Actors; } });
var GameBattler_1 = require("./objects/GameBattler");
Object.defineProperty(exports, "Game_Battler", { enumerable: true, get: function () { return GameBattler_1.Game_Battler; } });
var GameBattlerBase_1 = require("./objects/GameBattlerBase");
Object.defineProperty(exports, "Game_BattlerBase", { enumerable: true, get: function () { return GameBattlerBase_1.Game_BattlerBase; } });
var GameCharacter_1 = require("./objects/GameCharacter");
Object.defineProperty(exports, "Game_Character", { enumerable: true, get: function () { return GameCharacter_1.Game_Character; } });
var GameCharacterBase_1 = require("./objects/GameCharacterBase");
Object.defineProperty(exports, "Game_CharacterBase", { enumerable: true, get: function () { return GameCharacterBase_1.Game_CharacterBase; } });
var GameCommonEvent_1 = require("./objects/GameCommonEvent");
Object.defineProperty(exports, "Game_CommonEvent", { enumerable: true, get: function () { return GameCommonEvent_1.Game_CommonEvent; } });
var GameEnemy_1 = require("./objects/GameEnemy");
Object.defineProperty(exports, "Game_Enemy", { enumerable: true, get: function () { return GameEnemy_1.Game_Enemy; } });
var GameEvent_1 = require("./objects/GameEvent");
Object.defineProperty(exports, "Game_Event", { enumerable: true, get: function () { return GameEvent_1.Game_Event; } });
var GameFollower_1 = require("./objects/GameFollower");
Object.defineProperty(exports, "Game_Follower", { enumerable: true, get: function () { return GameFollower_1.Game_Follower; } });
var GameFollowers_1 = require("./objects/GameFollowers");
Object.defineProperty(exports, "Game_Followers", { enumerable: true, get: function () { return GameFollowers_1.Game_Followers; } });
var GameInterpreter_1 = require("./objects/GameInterpreter");
Object.defineProperty(exports, "Game_Interpreter", { enumerable: true, get: function () { return GameInterpreter_1.Game_Interpreter; } });
var GameItem_1 = require("./objects/GameItem");
Object.defineProperty(exports, "Game_Item", { enumerable: true, get: function () { return GameItem_1.Game_Item; } });
var GameMap_1 = require("./objects/GameMap");
Object.defineProperty(exports, "Game_Map", { enumerable: true, get: function () { return GameMap_1.Game_Map; } });
var GameMessage_1 = require("./objects/GameMessage");
Object.defineProperty(exports, "Game_Message", { enumerable: true, get: function () { return GameMessage_1.Game_Message; } });
var GameParty_1 = require("./objects/GameParty");
Object.defineProperty(exports, "Game_Party", { enumerable: true, get: function () { return GameParty_1.Game_Party; } });
var GamePicture_1 = require("./objects/GamePicture");
Object.defineProperty(exports, "Game_Picture", { enumerable: true, get: function () { return GamePicture_1.Game_Picture; } });
var GamePlayer_1 = require("./objects/GamePlayer");
Object.defineProperty(exports, "Game_Player", { enumerable: true, get: function () { return GamePlayer_1.Game_Player; } });
var GameScreen_1 = require("./objects/GameScreen");
Object.defineProperty(exports, "Game_Screen", { enumerable: true, get: function () { return GameScreen_1.Game_Screen; } });
var GameSelfSwitches_1 = require("./objects/GameSelfSwitches");
Object.defineProperty(exports, "Game_SelfSwitches", { enumerable: true, get: function () { return GameSelfSwitches_1.Game_SelfSwitches; } });
var GameSwitches_1 = require("./objects/GameSwitches");
Object.defineProperty(exports, "Game_Switches", { enumerable: true, get: function () { return GameSwitches_1.Game_Switches; } });
var GameSystem_1 = require("./objects/GameSystem");
Object.defineProperty(exports, "Game_System", { enumerable: true, get: function () { return GameSystem_1.Game_System; } });
var GameTemp_1 = require("./objects/GameTemp");
Object.defineProperty(exports, "Game_Temp", { enumerable: true, get: function () { return GameTemp_1.Game_Temp; } });
var GameTimer_1 = require("./objects/GameTimer");
Object.defineProperty(exports, "Game_Timer", { enumerable: true, get: function () { return GameTimer_1.Game_Timer; } });
var GameTroop_1 = require("./objects/GameTroop");
Object.defineProperty(exports, "Game_Troop", { enumerable: true, get: function () { return GameTroop_1.Game_Troop; } });
var GameUnit_1 = require("./objects/GameUnit");
Object.defineProperty(exports, "Game_Unit", { enumerable: true, get: function () { return GameUnit_1.Game_Unit; } });
var GameVariables_1 = require("./objects/GameVariables");
Object.defineProperty(exports, "Game_Variables", { enumerable: true, get: function () { return GameVariables_1.Game_Variables; } });
var GameVehicle_1 = require("./objects/GameVehicle");
Object.defineProperty(exports, "Game_Vehicle", { enumerable: true, get: function () { return GameVehicle_1.Game_Vehicle; } });
__exportStar(require("./PIXI"), exports);
var SceneBase_1 = require("./scenes/SceneBase");
Object.defineProperty(exports, "Scene_Base", { enumerable: true, get: function () { return SceneBase_1.Scene_Base; } });
var SceneBattle_1 = require("./scenes/SceneBattle");
Object.defineProperty(exports, "Scene_Battle", { enumerable: true, get: function () { return SceneBattle_1.Scene_Battle; } });
var SceneBoot_1 = require("./scenes/SceneBoot");
Object.defineProperty(exports, "Scene_Boot", { enumerable: true, get: function () { return SceneBoot_1.Scene_Boot; } });
var SceneEquip_1 = require("./scenes/SceneEquip");
Object.defineProperty(exports, "Scene_Equip", { enumerable: true, get: function () { return SceneEquip_1.Scene_Equip; } });
var SceneGameEnd_1 = require("./scenes/SceneGameEnd");
Object.defineProperty(exports, "Scene_GameEnd", { enumerable: true, get: function () { return SceneGameEnd_1.Scene_GameEnd; } });
var SceneGameOver_1 = require("./scenes/SceneGameOver");
Object.defineProperty(exports, "Scene_Gameover", { enumerable: true, get: function () { return SceneGameOver_1.Scene_Gameover; } });
var SceneItem_1 = require("./scenes/SceneItem");
Object.defineProperty(exports, "Scene_Item", { enumerable: true, get: function () { return SceneItem_1.Scene_Item; } });
var SceneItemBase_1 = require("./scenes/SceneItemBase");
Object.defineProperty(exports, "Scene_ItemBase", { enumerable: true, get: function () { return SceneItemBase_1.Scene_ItemBase; } });
var SceneMap_1 = require("./scenes/SceneMap");
Object.defineProperty(exports, "Scene_Map", { enumerable: true, get: function () { return SceneMap_1.Scene_Map; } });
var SceneMenu_1 = require("./scenes/SceneMenu");
Object.defineProperty(exports, "Scene_Menu", { enumerable: true, get: function () { return SceneMenu_1.Scene_Menu; } });
var SceneMenuBase_1 = require("./scenes/SceneMenuBase");
Object.defineProperty(exports, "Scene_MenuBase", { enumerable: true, get: function () { return SceneMenuBase_1.Scene_MenuBase; } });
var SceneOptions_1 = require("./scenes/SceneOptions");
Object.defineProperty(exports, "Scene_Options", { enumerable: true, get: function () { return SceneOptions_1.Scene_Options; } });
var SceneShop_1 = require("./scenes/SceneShop");
Object.defineProperty(exports, "Scene_Shop", { enumerable: true, get: function () { return SceneShop_1.Scene_Shop; } });
var SceneSkill_1 = require("./scenes/SceneSkill");
Object.defineProperty(exports, "Scene_Skill", { enumerable: true, get: function () { return SceneSkill_1.Scene_Skill; } });
var SceneStatus_1 = require("./scenes/SceneStatus");
Object.defineProperty(exports, "Scene_Status", { enumerable: true, get: function () { return SceneStatus_1.Scene_Status; } });
var SceneTitle_1 = require("./scenes/SceneTitle");
Object.defineProperty(exports, "Scene_Title", { enumerable: true, get: function () { return SceneTitle_1.Scene_Title; } });
var SceneFile_1 = require("./scenes/SceneFile");
Object.defineProperty(exports, "Scene_File", { enumerable: true, get: function () { return SceneFile_1.Scene_File; } });
var SceneLoad_1 = require("./scenes/SceneLoad");
Object.defineProperty(exports, "Scene_Load", { enumerable: true, get: function () { return SceneLoad_1.Scene_Load; } });
var SceneSave_1 = require("./scenes/SceneSave");
Object.defineProperty(exports, "Scene_Save", { enumerable: true, get: function () { return SceneSave_1.Scene_Save; } });
var SpriteActor_1 = require("./sprites/SpriteActor");
Object.defineProperty(exports, "Sprite_Actor", { enumerable: true, get: function () { return SpriteActor_1.Sprite_Actor; } });
var SpriteAnimation_1 = require("./sprites/SpriteAnimation");
Object.defineProperty(exports, "Sprite_Animation", { enumerable: true, get: function () { return SpriteAnimation_1.Sprite_Animation; } });
var SpriteBalloon_1 = require("./sprites/SpriteBalloon");
Object.defineProperty(exports, "Sprite_Balloon", { enumerable: true, get: function () { return SpriteBalloon_1.Sprite_Balloon; } });
var SpriteBase_1 = require("./sprites/SpriteBase");
Object.defineProperty(exports, "Sprite_Base", { enumerable: true, get: function () { return SpriteBase_1.Sprite_Base; } });
var SpriteBattler_1 = require("./sprites/SpriteBattler");
Object.defineProperty(exports, "Sprite_Battler", { enumerable: true, get: function () { return SpriteBattler_1.Sprite_Battler; } });
var SpriteCharacter_1 = require("./sprites/SpriteCharacter");
Object.defineProperty(exports, "Sprite_Character", { enumerable: true, get: function () { return SpriteCharacter_1.Sprite_Character; } });
var SpriteDamage_1 = require("./sprites/SpriteDamage");
Object.defineProperty(exports, "Sprite_Damage", { enumerable: true, get: function () { return SpriteDamage_1.Sprite_Damage; } });
var SpriteDestination_1 = require("./sprites/SpriteDestination");
Object.defineProperty(exports, "Sprite_Destination", { enumerable: true, get: function () { return SpriteDestination_1.Sprite_Destination; } });
var SpriteEnemy_1 = require("./sprites/SpriteEnemy");
Object.defineProperty(exports, "Sprite_Enemy", { enumerable: true, get: function () { return SpriteEnemy_1.Sprite_Enemy; } });
var SpritePicture_1 = require("./sprites/SpritePicture");
Object.defineProperty(exports, "Sprite_Picture", { enumerable: true, get: function () { return SpritePicture_1.Sprite_Picture; } });
var SpriteStateIcon_1 = require("./sprites/SpriteStateIcon");
Object.defineProperty(exports, "Sprite_StateIcon", { enumerable: true, get: function () { return SpriteStateIcon_1.Sprite_StateIcon; } });
var SpriteStateOverlay_1 = require("./sprites/SpriteStateOverlay");
Object.defineProperty(exports, "Sprite_StateOverlay", { enumerable: true, get: function () { return SpriteStateOverlay_1.Sprite_StateOverlay; } });
var SpriteTimer_1 = require("./sprites/SpriteTimer");
Object.defineProperty(exports, "Sprite_Timer", { enumerable: true, get: function () { return SpriteTimer_1.Sprite_Timer; } });
var SpriteWeapon_1 = require("./sprites/SpriteWeapon");
Object.defineProperty(exports, "Sprite_Weapon", { enumerable: true, get: function () { return SpriteWeapon_1.Sprite_Weapon; } });
var SpritesetBase_1 = require("./sprites/SpritesetBase");
Object.defineProperty(exports, "Spriteset_Base", { enumerable: true, get: function () { return SpritesetBase_1.Spriteset_Base; } });
var SpritesetBattle_1 = require("./sprites/SpritesetBattle");
Object.defineProperty(exports, "Spriteset_Battle", { enumerable: true, get: function () { return SpritesetBattle_1.Spriteset_Battle; } });
var SpritesetMap_1 = require("./sprites/SpritesetMap");
Object.defineProperty(exports, "Spriteset_Map", { enumerable: true, get: function () { return SpritesetMap_1.Spriteset_Map; } });
var WindowActorCommand_1 = require("./windows/WindowActorCommand");
Object.defineProperty(exports, "Window_ActorCommand", { enumerable: true, get: function () { return WindowActorCommand_1.Window_ActorCommand; } });
var WindowBase_1 = require("./windows/WindowBase");
Object.defineProperty(exports, "Window_Base", { enumerable: true, get: function () { return WindowBase_1.Window_Base; } });
var WindowBattleActor_1 = require("./windows/WindowBattleActor");
Object.defineProperty(exports, "Window_BattleActor", { enumerable: true, get: function () { return WindowBattleActor_1.Window_BattleActor; } });
var WindowBattleEnemy_1 = require("./windows/WindowBattleEnemy");
Object.defineProperty(exports, "Window_BattleEnemy", { enumerable: true, get: function () { return WindowBattleEnemy_1.Window_BattleEnemy; } });
var WindowBattleItem_1 = require("./windows/WindowBattleItem");
Object.defineProperty(exports, "Window_BattleItem", { enumerable: true, get: function () { return WindowBattleItem_1.Window_BattleItem; } });
var WindowBattleLog_1 = require("./windows/WindowBattleLog");
Object.defineProperty(exports, "Window_BattleLog", { enumerable: true, get: function () { return WindowBattleLog_1.Window_BattleLog; } });
var WindowBattleSkill_1 = require("./windows/WindowBattleSkill");
Object.defineProperty(exports, "Window_BattleSkill", { enumerable: true, get: function () { return WindowBattleSkill_1.Window_BattleSkill; } });
var WindowChoiceList_1 = require("./windows/WindowChoiceList");
Object.defineProperty(exports, "Window_ChoiceList", { enumerable: true, get: function () { return WindowChoiceList_1.Window_ChoiceList; } });
var WindowCommand_1 = require("./windows/WindowCommand");
Object.defineProperty(exports, "Window_Command", { enumerable: true, get: function () { return WindowCommand_1.Window_Command; } });
var WindowEquipCommand_1 = require("./windows/WindowEquipCommand");
Object.defineProperty(exports, "Window_EquipCommand", { enumerable: true, get: function () { return WindowEquipCommand_1.Window_EquipCommand; } });
var WindowEquipItem_1 = require("./windows/WindowEquipItem");
Object.defineProperty(exports, "Window_EquipItem", { enumerable: true, get: function () { return WindowEquipItem_1.Window_EquipItem; } });
var WindowEquipSlot_1 = require("./windows/WindowEquipSlot");
Object.defineProperty(exports, "Window_EquipSlot", { enumerable: true, get: function () { return WindowEquipSlot_1.Window_EquipSlot; } });
var WindowEquipStatus_1 = require("./windows/WindowEquipStatus");
Object.defineProperty(exports, "Window_EquipStatus", { enumerable: true, get: function () { return WindowEquipStatus_1.Window_EquipStatus; } });
var WindowEventItem_1 = require("./windows/WindowEventItem");
Object.defineProperty(exports, "Window_EventItem", { enumerable: true, get: function () { return WindowEventItem_1.Window_EventItem; } });
var WindowGameEnd_1 = require("./windows/WindowGameEnd");
Object.defineProperty(exports, "Window_GameEnd", { enumerable: true, get: function () { return WindowGameEnd_1.Window_GameEnd; } });
var WindowGold_1 = require("./windows/WindowGold");
Object.defineProperty(exports, "Window_Gold", { enumerable: true, get: function () { return WindowGold_1.Window_Gold; } });
var WindowHelp_1 = require("./windows/WindowHelp");
Object.defineProperty(exports, "Window_Help", { enumerable: true, get: function () { return WindowHelp_1.Window_Help; } });
var WindowHorzCommand_1 = require("./windows/WindowHorzCommand");
Object.defineProperty(exports, "Window_HorzCommand", { enumerable: true, get: function () { return WindowHorzCommand_1.Window_HorzCommand; } });
var WindowItemCategory_1 = require("./windows/WindowItemCategory");
Object.defineProperty(exports, "Window_ItemCategory", { enumerable: true, get: function () { return WindowItemCategory_1.Window_ItemCategory; } });
var WindowItemList_1 = require("./windows/WindowItemList");
Object.defineProperty(exports, "Window_ItemList", { enumerable: true, get: function () { return WindowItemList_1.Window_ItemList; } });
var WindowMapName_1 = require("./windows/WindowMapName");
Object.defineProperty(exports, "Window_MapName", { enumerable: true, get: function () { return WindowMapName_1.Window_MapName; } });
var WindowMenuActor_1 = require("./windows/WindowMenuActor");
Object.defineProperty(exports, "Window_MenuActor", { enumerable: true, get: function () { return WindowMenuActor_1.Window_MenuActor; } });
var WindowMenuCommand_1 = require("./windows/WindowMenuCommand");
Object.defineProperty(exports, "Window_MenuCommand", { enumerable: true, get: function () { return WindowMenuCommand_1.Window_MenuCommand; } });
var WindowMenuStatus_1 = require("./windows/WindowMenuStatus");
Object.defineProperty(exports, "Window_MenuStatus", { enumerable: true, get: function () { return WindowMenuStatus_1.Window_MenuStatus; } });
var WindowMessage_1 = require("./windows/WindowMessage");
Object.defineProperty(exports, "Window_Message", { enumerable: true, get: function () { return WindowMessage_1.Window_Message; } });
var WindowNumberInput_1 = require("./windows/WindowNumberInput");
Object.defineProperty(exports, "Window_NumberInput", { enumerable: true, get: function () { return WindowNumberInput_1.Window_NumberInput; } });
var WindowOptions_1 = require("./windows/WindowOptions");
Object.defineProperty(exports, "Window_Options", { enumerable: true, get: function () { return WindowOptions_1.Window_Options; } });
var WindowPartyCommand_1 = require("./windows/WindowPartyCommand");
Object.defineProperty(exports, "Window_PartyCommand", { enumerable: true, get: function () { return WindowPartyCommand_1.Window_PartyCommand; } });
var WindowScrollText_1 = require("./windows/WindowScrollText");
Object.defineProperty(exports, "Window_ScrollText", { enumerable: true, get: function () { return WindowScrollText_1.Window_ScrollText; } });
var WindowSelectable_1 = require("./windows/WindowSelectable");
Object.defineProperty(exports, "Window_Selectable", { enumerable: true, get: function () { return WindowSelectable_1.Window_Selectable; } });
var WindowShopBuy_1 = require("./windows/WindowShopBuy");
Object.defineProperty(exports, "Window_ShopBuy", { enumerable: true, get: function () { return WindowShopBuy_1.Window_ShopBuy; } });
var WindowShopCommand_1 = require("./windows/WindowShopCommand");
Object.defineProperty(exports, "Window_ShopCommand", { enumerable: true, get: function () { return WindowShopCommand_1.Window_ShopCommand; } });
var WindowShopNumber_1 = require("./windows/WindowShopNumber");
Object.defineProperty(exports, "Window_ShopNumber", { enumerable: true, get: function () { return WindowShopNumber_1.Window_ShopNumber; } });
var WindowShopSell_1 = require("./windows/WindowShopSell");
Object.defineProperty(exports, "Window_ShopSell", { enumerable: true, get: function () { return WindowShopSell_1.Window_ShopSell; } });
var WindowShopStatus_1 = require("./windows/WindowShopStatus");
Object.defineProperty(exports, "Window_ShopStatus", { enumerable: true, get: function () { return WindowShopStatus_1.Window_ShopStatus; } });
var WindowSkillList_1 = require("./windows/WindowSkillList");
Object.defineProperty(exports, "Window_SkillList", { enumerable: true, get: function () { return WindowSkillList_1.Window_SkillList; } });
var WindowSkillStatus_1 = require("./windows/WindowSkillStatus");
Object.defineProperty(exports, "Window_SkillStatus", { enumerable: true, get: function () { return WindowSkillStatus_1.Window_SkillStatus; } });
var WindowSkillType_1 = require("./windows/WindowSkillType");
Object.defineProperty(exports, "Window_SkillType", { enumerable: true, get: function () { return WindowSkillType_1.Window_SkillType; } });
var WindowStatus_1 = require("./windows/WindowStatus");
Object.defineProperty(exports, "Window_Status", { enumerable: true, get: function () { return WindowStatus_1.Window_Status; } });
var WindowTitleCommand_1 = require("./windows/WindowTitleCommand");
Object.defineProperty(exports, "Window_TitleCommand", { enumerable: true, get: function () { return WindowTitleCommand_1.Window_TitleCommand; } });
var WindowSavefileList_1 = require("./windows/WindowSavefileList");
Object.defineProperty(exports, "Window_SavefileList", { enumerable: true, get: function () { return WindowSavefileList_1.Window_SavefileList; } });
