"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PluginManager = exports.SoundManager = exports.BattleManager = exports.TextManager = exports.DataManager = exports.ImageManager = exports.AudioManager = exports.SceneManager = void 0;
var SceneManager_1 = require("./SceneManager");
Object.defineProperty(exports, "SceneManager", { enumerable: true, get: function () { return SceneManager_1.SceneManager; } });
var AudioManager_1 = require("./AudioManager");
Object.defineProperty(exports, "AudioManager", { enumerable: true, get: function () { return AudioManager_1.AudioManager; } });
var ImageManager_1 = require("./ImageManager");
Object.defineProperty(exports, "ImageManager", { enumerable: true, get: function () { return ImageManager_1.ImageManager; } });
var DataManager_1 = require("./DataManager");
Object.defineProperty(exports, "DataManager", { enumerable: true, get: function () { return DataManager_1.DataManager; } });
var TextManager_1 = require("./TextManager");
Object.defineProperty(exports, "TextManager", { enumerable: true, get: function () { return TextManager_1.TextManager; } });
var BattleManager_1 = require("./BattleManager");
Object.defineProperty(exports, "BattleManager", { enumerable: true, get: function () { return BattleManager_1.BattleManager; } });
var SoundManager_1 = require("./SoundManager");
Object.defineProperty(exports, "SoundManager", { enumerable: true, get: function () { return SoundManager_1.SoundManager; } });
var PluginManager_1 = require("./PluginManager");
Object.defineProperty(exports, "PluginManager", { enumerable: true, get: function () { return PluginManager_1.PluginManager; } });
