"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Game_Interpreter = exports.Game_SelfSwitches = exports.Game_Variables = exports.Game_Item = exports.Game_Temp = exports.Game_Screen = exports.Game_Character = exports.Game_Battler = exports.Game_Action = exports.Game_Map = exports.Game_Troop = exports.Game_Enemy = exports.Game_Message = exports.Game_Timer = exports.Game_System = exports.Game_Actors = exports.Game_Actor = exports.Game_Party = exports.Game_Player = void 0;
var GamePlayer_1 = require("./GamePlayer");
Object.defineProperty(exports, "Game_Player", { enumerable: true, get: function () { return GamePlayer_1.Game_Player; } });
var GameParty_1 = require("./GameParty");
Object.defineProperty(exports, "Game_Party", { enumerable: true, get: function () { return GameParty_1.Game_Party; } });
var GameActor_1 = require("./GameActor");
Object.defineProperty(exports, "Game_Actor", { enumerable: true, get: function () { return GameActor_1.Game_Actor; } });
var GameActors_1 = require("./GameActors");
Object.defineProperty(exports, "Game_Actors", { enumerable: true, get: function () { return GameActors_1.Game_Actors; } });
var GameSystem_1 = require("./GameSystem");
Object.defineProperty(exports, "Game_System", { enumerable: true, get: function () { return GameSystem_1.Game_System; } });
var GameTimer_1 = require("./GameTimer");
Object.defineProperty(exports, "Game_Timer", { enumerable: true, get: function () { return GameTimer_1.Game_Timer; } });
var GameMessage_1 = require("./GameMessage");
Object.defineProperty(exports, "Game_Message", { enumerable: true, get: function () { return GameMessage_1.Game_Message; } });
var GameEnemy_1 = require("./GameEnemy");
Object.defineProperty(exports, "Game_Enemy", { enumerable: true, get: function () { return GameEnemy_1.Game_Enemy; } });
var GameTroop_1 = require("./GameTroop");
Object.defineProperty(exports, "Game_Troop", { enumerable: true, get: function () { return GameTroop_1.Game_Troop; } });
var GameMap_1 = require("./GameMap");
Object.defineProperty(exports, "Game_Map", { enumerable: true, get: function () { return GameMap_1.Game_Map; } });
var GameAction_1 = require("./GameAction");
Object.defineProperty(exports, "Game_Action", { enumerable: true, get: function () { return GameAction_1.Game_Action; } });
var GameBattler_1 = require("./GameBattler");
Object.defineProperty(exports, "Game_Battler", { enumerable: true, get: function () { return GameBattler_1.Game_Battler; } });
var GameCharacter_1 = require("./GameCharacter");
Object.defineProperty(exports, "Game_Character", { enumerable: true, get: function () { return GameCharacter_1.Game_Character; } });
var GameScreen_1 = require("./GameScreen");
Object.defineProperty(exports, "Game_Screen", { enumerable: true, get: function () { return GameScreen_1.Game_Screen; } });
var GameTemp_1 = require("./GameTemp");
Object.defineProperty(exports, "Game_Temp", { enumerable: true, get: function () { return GameTemp_1.Game_Temp; } });
var GameItem_1 = require("./GameItem");
Object.defineProperty(exports, "Game_Item", { enumerable: true, get: function () { return GameItem_1.Game_Item; } });
var GameVariables_1 = require("./GameVariables");
Object.defineProperty(exports, "Game_Variables", { enumerable: true, get: function () { return GameVariables_1.Game_Variables; } });
var GameSelfSwitches_1 = require("./GameSelfSwitches");
Object.defineProperty(exports, "Game_SelfSwitches", { enumerable: true, get: function () { return GameSelfSwitches_1.Game_SelfSwitches; } });
var GameInterpreter_1 = require("./GameInterpreter");
Object.defineProperty(exports, "Game_Interpreter", { enumerable: true, get: function () { return GameInterpreter_1.Game_Interpreter; } });
