"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Scene_Boot = exports.PluginManager = exports.AudioManager = exports.SceneManager = exports.TouchInput = exports.Graphics = void 0;
var core_1 = require("./core");
Object.defineProperty(exports, "Graphics", { enumerable: true, get: function () { return core_1.Graphics; } });
Object.defineProperty(exports, "TouchInput", { enumerable: true, get: function () { return core_1.TouchInput; } });
var managers_1 = require("./managers");
Object.defineProperty(exports, "SceneManager", { enumerable: true, get: function () { return managers_1.SceneManager; } });
Object.defineProperty(exports, "AudioManager", { enumerable: true, get: function () { return managers_1.AudioManager; } });
Object.defineProperty(exports, "PluginManager", { enumerable: true, get: function () { return managers_1.PluginManager; } });
var scenes_1 = require("./scenes");
Object.defineProperty(exports, "Scene_Boot", { enumerable: true, get: function () { return scenes_1.Scene_Boot; } });
